"""Main orchestration pipeline for AutoDev Agent."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from .codegen import ProjectScaffolder
from .config import AgentConfig
from .correction import CorrectionEngine
from .documentation import generate_readme
from .git_workflow import GitWorkflow
from .github_manager import GitHubManager
from .idea_generator import IdeaGenerator
from .memory import MemoryStore
from .models import RunRecord, ValidationResult
from .planner import ArchitecturePlanner
from .scheduler import SchedulerLock
from .security import SecurityScanner
from .validator import Validator


class AutoDevOrchestrator:
    """Coordinates generation, validation, correction, and contribution workflow."""

    def __init__(self, config: AgentConfig | None = None) -> None:
        self.config = config or AgentConfig()
        self.config.ensure_dirs()
        self.memory = MemoryStore(self.config.memory_db_path)
        self.idea_generator = IdeaGenerator()
        self.planner = ArchitecturePlanner()
        self.validator = Validator()
        self.scheduler = SchedulerLock(
            self.config.schedule_lock_file, stale_after_seconds=self.config.lock_stale_seconds
        )
        self.scaffolder = ProjectScaffolder()
        self.correction_engine = CorrectionEngine()
        self.security_scanner = SecurityScanner()

    def run_once(self) -> bool:
        """Execute one autonomous cycle with retry-aware logging and correction hooks."""
        if not self.scheduler.acquire():
            return False

        started = datetime.now(tz=timezone.utc)
        retries = 0
        success = False
        project_name = "n/a"

        try:
            idea = self.idea_generator.generate(
                existing_names=self.memory.list_project_names(),
                min_complexity=self.config.min_complexity,
                max_complexity=self.config.max_complexity,
            )
            project_name = idea.name
            plan = self.planner.create_plan(idea, self.config)
            generated = self.scaffolder.generate(
                workspace_root=self.config.workspace_root,
                idea=idea,
                plan=plan,
                readme_text=generate_readme(idea, plan),
                config=self.config,
            )
            project_root = generated.root
            self.memory.store_project(idea.name, idea.category, idea.complexity)
            self.security_scanner.scan(project_root)

            while retries <= self.config.max_retries:
                validation = self.validator.run(
                    project_root,
                    run_lint=self.config.run_lint,
                    run_type_check=self.config.run_type_check,
                    run_coverage=self.config.run_coverage,
                    min_coverage=self.config.min_test_coverage,
                    strict_validation=self.config.strict_validation,
                )
                self._write_validation_log(project_root, retries, validation)
                if validation.success:
                    success = True
                    if self.config.auto_git:
                        self._publish_changes(project_name)
                    break
                retries += 1
                self.correction_engine.apply(project_root, validation)

            return success
        finally:
            finished = datetime.now(tz=timezone.utc)
            self.memory.store_run(
                RunRecord(
                    started_at=started,
                    finished_at=finished,
                    project_name=project_name,
                    retries=retries,
                    success=success,
                )
            )
            self.scheduler.release()

    def _publish_changes(self, project_name: str) -> None:
        """Create branch/commit and optionally open a pull request."""
        repo_root = Path.cwd()
        git = GitWorkflow(repo_root)
        branch = git.create_or_checkout_feature_branch(project_name)
        git.commit_project(project_name)
        if not self.config.auto_pr:
            return
        manager = GitHubManager(self.config.github_repo)
        manager.create_pull_request(
            title=f"feat: add {project_name} with tests and documentation",
            body="Automated contribution generated by AutoDev Agent.",
            head=branch,
            base="main",
        )

    @staticmethod
    def _write_validation_log(project_root: Path, attempt: int, result: ValidationResult) -> None:
        log_file = project_root / "validation_log.jsonl"
        entry = {
            "attempt": attempt,
            "success": result.success,
            "checks": result.checks,
            "logs": result.logs,
        }
        with log_file.open("a", encoding="utf-8") as handle:
            handle.write(json.dumps(entry) + "\n")
